
package lc.client.webservice.wscode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServerWebServiceImplService", targetNamespace = "http://webservice.server.lc/", wsdlLocation = "http://localhost:9998/service?wsdl")
public class ServerWebServiceImplService
    extends Service
{

    private final static URL SERVERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9998/service?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SERVERWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    /**
     * 指定远程服务地址和服务命名空间
     * @param wsdlLocation
     * @param serviceName
     */
    public ServerWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerWebServiceImplService() {
        super(SERVERWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://webservice.server.lc/", "ServerWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ServerWebService
     */
    @WebEndpoint(name = "ServerWebServiceImplPort")
    public ServerWebService getServerWebServiceImplPort() {
        return (ServerWebService)super.getPort(new QName("http://webservice.server.lc/", "ServerWebServiceImplPort"), ServerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerWebService
     */
    @WebEndpoint(name = "ServerWebServiceImplPort")
    public ServerWebService getServerWebServiceImplPort(WebServiceFeature... features) {
        return (ServerWebService)super.getPort(new QName("http://webservice.server.lc/", "ServerWebServiceImplPort"), ServerWebService.class, features);
    }

}
