
package lc.client.webservice.wscode;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import lc.client.environment.UserInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServerWebService", targetNamespace = "http://webservice.service.server.lc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerWebService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns lc.client.webservice.wscode.MsgEntry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.RegisterResponse")
    public MsgEntry register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns lc.client.webservice.wscode.MsgEntry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.LoginResponse")
    public MsgEntry login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns lc.client.webservice.wscode.MsgEntry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createGame", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.CreateGame")
    @ResponseWrapper(localName = "createGameResponse", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.CreateGameResponse")
    public MsgEntry createGame(
        @WebParam(name = "arg0", targetNamespace = "")
        GameHouse arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<lc.client.webservice.wscode.GameHouse>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameHouses", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.GetGameHouses")
    @ResponseWrapper(localName = "getGameHousesResponse", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.GetGameHousesResponse")
    public List<GameHouse> getGameHouses();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns lc.client.webservice.wscode.MsgEntry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "joinGame", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.JoinGame")
    @ResponseWrapper(localName = "joinGameResponse", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.JoinGameResponse")
    public MsgEntry joinGame(
        @WebParam(name = "arg0", targetNamespace = "")
        UserInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns lc.client.webservice.wscode.UserInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayer", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.GetPlayer")
    @ResponseWrapper(localName = "getPlayerResponse", targetNamespace = "http://webservice.service.server.lc/", className = "lc.client.webservice.wscode.GetPlayerResponse")
    public UserInfo getPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
